-- DEV_USER."user" definition
ALTER session SET container=XEPDB1;

CREATE TABLE "DEV_USER"."user" 
   (	"id" VARCHAR2(36), 
	"name" VARCHAR2(255) NOT NULL ENABLE, 
	"created_at" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE, 
	"updated_at" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP NOT NULL ENABLE, 
	 CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "DEV_USER"."PK_cace4a159ff9f2512dd42373760" ON "DEV_USER"."user" ("id") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;